import {
	ContributionsMapSchema,
	ContributionSchema,
	type Contribution,
	type ContributionsMap,
} from "../schema/contribution";
import { readJsoncSync, writeJsoncSync, resolveDataPath } from "../utils/jsonc";

const FILE_URL = resolveDataPath(
	"../data/contributions.jsonc",
	import.meta.url,
);

/** Manages sprite contribution data */
export class ContributionRepository {
	private static cachedData: ContributionsMap | null = null;

	private static loadData(): ContributionsMap {
		if (this.cachedData) return this.cachedData;
		const json = readJsoncSync(FILE_URL);
		this.cachedData = ContributionsMapSchema.parse(json);
		return this.cachedData;
	}

	/** Sets isolated mock data for testing */
	static setData(data: ContributionsMap): void {
		this.cachedData = data;
	}

	/** Resets data to original production state */
	static reset(): void {
		this.cachedData = null;
	}

	/** Returns contributions for a specific sprite URL */
	static getContribution(spriteUrl: string): Contribution[] {
		const data = this.loadData();
		// Exact match
		const contributions = data[spriteUrl];
		if (contributions) return contributions;

		return [];
	}

	/** Adds a contribution to a sprite URL */
	static addContribution(spriteUrl: string, contribution: Contribution): void {
		const data = this.loadData();
		const validatedContribution = ContributionSchema.parse(contribution);
		if (!data[spriteUrl]) {
			data[spriteUrl] = [];
		}
		// Prevent duplicates
		const alreadyExists = data[spriteUrl].some(
			(c) =>
				c.contributorId === validatedContribution.contributorId &&
				c.relation === validatedContribution.relation,
		);
		if (!alreadyExists) {
			data[spriteUrl].push(validatedContribution);
		}
	}

	/** Persists the data back to contributions.jsonc */
	static async save(): Promise<void> {
		const data = this.loadData();
		const header =
			"// This file is auto-generated by parser. Do not edit manually.";
		writeJsoncSync(FILE_URL, data, header);
	}
}
