import contributionsJson from "../data/contributions.jsonc"
import { ContributionsMapSchema, ContributionSchema, type Contribution, type ContributionsMap } from "../schema/contribution";
import { join } from "path";

/** Manages sprite contribution data */
export class ContributionRepository {
  static data: ContributionsMap = ContributionsMapSchema.parse(contributionsJson)

  /** Returns contributions for a specific sprite URL */
  static getContribution(spriteUrl: string): Contribution[] {
    // Exact match
    const contributions = this.data[spriteUrl];
    if (contributions) return contributions;

    // Fallback: match by filename if URL is not an exact match
    // Some URLs might have slightly different commit hashes but same content if they were rebased
    // or if the parser is looking at a different commit.
    // However, the requested logic is to check database first.
    return [];
  }

  /** Adds a contribution to a sprite URL */
  static addContribution(spriteUrl: string, contribution: Contribution): void {
    const validatedContribution = ContributionSchema.parse(contribution);
    if (!this.data[spriteUrl]) {
      this.data[spriteUrl] = [];
    }
    // Prevent duplicates
    const alreadyExists = this.data[spriteUrl].some(
      c => c.contributorId === validatedContribution.contributorId && c.relation === validatedContribution.relation
    );
    if (!alreadyExists) {
      this.data[spriteUrl].push(validatedContribution);
    }
  }

  /** Persists the data back to contributions.jsonc */
  static async save(): Promise<void> {
    const filePath = join(import.meta.dirname, "../data/contributions.jsonc");
    const content = "// This file is auto-generated by parser. Do not edit manually.\n" + 
      JSON.stringify(this.data, null, 2);
    await Bun.write(filePath, content);
  }
}
