import {
	type Contribution,
	ContributionSchema,
	type ContributionsMap,
	ContributionsMapSchema,
} from "../schema/contribution";
import { readJsoncSync, resolveDataPath, writeJsoncSync } from "../utils/jsonc";

const FILE_URL = resolveDataPath(
	"../data/contributions.jsonc",
	import.meta.url,
);

let cachedData: ContributionsMap | null = null;

function loadData(): ContributionsMap {
	if (cachedData) return cachedData;
	const json = readJsoncSync(FILE_URL);
	cachedData = ContributionsMapSchema.parse(json);
	return cachedData;
}

/** Sets isolated mock data for testing */
function setData(data: ContributionsMap): void {
	cachedData = data;
}

/** Resets data to original production state */
function reset(): void {
	cachedData = null;
}

/** Returns contributions for a specific sprite URL */
function getContribution(spriteUrl: string): Contribution[] {
	const data = loadData();
	// Exact match
	const contributions = data[spriteUrl];
	if (contributions) return contributions;

	return [];
}

/** Adds a contribution to a sprite URL */
function addContribution(
	spriteUrl: string,
	contribution: Contribution,
): void {
	const data = loadData();
	const validatedContribution = ContributionSchema.parse(contribution);
	if (!data[spriteUrl]) {
		data[spriteUrl] = [];
	}
	// Prevent duplicates
	const alreadyExists = data[spriteUrl].some(
		(c) =>
			c.contributorId === validatedContribution.contributorId &&
			c.relation === validatedContribution.relation,
	);
	if (!alreadyExists) {
		data[spriteUrl].push(validatedContribution);
	}
}

/** Persists the data back to contributions.jsonc */
async function save(): Promise<void> {
	const data = loadData();
	const header =
		"// This file is auto-generated by parser. Do not edit manually.";
	writeJsoncSync(FILE_URL, data, header);
}

export const ContributionRepository = {
	setData,
	reset,
	getContribution,
	addContribution,
	save,
};
