import spritesheetsJson from "../data/spritesheets.jsonc"
import { SpritesheetsMapSchema, SpritesheetSchema, type SpritesheetsMap, type Spritesheet } from "../schema/spritesheet"
import * as fs from "node:fs"
import * as path from "node:path"

/** Reads Spritesheet data from local FS and returns typed data */
export class SpritesheetRepository {
  static data: SpritesheetsMap = SpritesheetsMapSchema.parse(spritesheetsJson)

  /** Returns all spritesheets indexed by internal key */
  static getAllSpritesheets(): SpritesheetsMap {
    return this.data
  }

  /** Returns a spritesheet by its UUID */
  static getSpritesheetById(spritesheetId: string): Spritesheet {
    const spritesheet = Object.values(this.data).find(s => s.spritesheetId === spritesheetId)
    if (!spritesheet) {
      throw new Error(`Spritesheet with ID ${spritesheetId} not found`)
    }
    return spritesheet
  }

  /** Returns spritesheets for a specific commit SHA */
  static getSpritesheetsByCommit(commitSha: string): Spritesheet[] {
    return Object.values(this.data).filter(s => s.commitSha === commitSha)
  }

  /** Appends new spritesheet into spritesheets.jsonc and updates in-memory cache */
  static addSpritesheet(spriteCode: string, spritesheet: Spritesheet): void {
    const validatedSpritesheet = SpritesheetSchema.parse(spritesheet)
    const key = `${spriteCode.toUpperCase()}_${validatedSpritesheet.commitSha}_${Object.keys(this.data).length}`
    this.data[key] = validatedSpritesheet

    const filePath = path.join(__dirname, "../data/spritesheets.jsonc")
    const dirPath = path.dirname(filePath)
    
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true })
    }

    const content = `// This file is auto-generated by spritesheet-generator. Do not edit manually.\n${JSON.stringify(this.data, null, 2)}`
    fs.writeFileSync(filePath, content, "utf-8")
  }
}
