import { SpritesheetsMapSchema, SpritesheetSchema, type SpritesheetsMap, type Spritesheet } from "../schema/spritesheet"

const DATA_URL = new URL("../data/spritesheets.jsonc", import.meta.url)

/** Reads Spritesheet data from local FS and returns typed data */
export class SpritesheetRepository {
  private static cachedData: SpritesheetsMap | null = null;

  private static async loadData(): Promise<SpritesheetsMap> {
    if (this.cachedData) return this.cachedData;

    const file = Bun.file(DATA_URL);
    if (!(await file.exists())) {
      this.cachedData = {};
      return this.cachedData;
    }

    try {
      const content = await file.text();
      // More robust comment stripping that handles both // and /* */
      const jsonText = content
        .replace(/\/\*[\s\S]*?\*\/|([^:]|^)\/\/.*$/gm, '$1')
        .trim();
      
      if (!jsonText) {
        this.cachedData = {};
        return this.cachedData;
      }

      const json = JSON.parse(jsonText);
      this.cachedData = SpritesheetsMapSchema.parse(json)
      return this.cachedData
    } catch (e) {
      console.warn("SpritesheetRepository: Failed to load data, starting empty", e)
      this.cachedData = {};
      return this.cachedData
    }
  }

  /** Returns all spritesheets indexed by internal key */
  static async getAllSpritesheets(): Promise<SpritesheetsMap> {
    return this.loadData()
  }

  /** Returns a spritesheet by its UUID */
  static async getSpritesheetById(spritesheetId: string): Promise<Spritesheet> {
    const data = await this.loadData();
    const spritesheet = Object.values(data).find(s => s.spritesheetId === spritesheetId)
    if (!spritesheet) {
      throw new Error(`Spritesheet with ID ${spritesheetId} not found`)
    }
    return spritesheet
  }

  /** Returns spritesheets for a specific commit SHA */
  static async getSpritesheetsByCommit(commitSha: string): Promise<Spritesheet[]> {
    const data = await this.loadData();
    return Object.values(data).filter(s => s.commitSha === commitSha)
  }

  /** Appends new spritesheet into spritesheets.jsonc and saves the image file */
  static async addSpritesheet(spriteCode: string, spritesheet: Spritesheet, imageData: Uint8Array): Promise<void> {
    const data = await this.loadData();
    const validatedSpritesheet = SpritesheetSchema.parse(spritesheet)
    const key = `${spriteCode.toUpperCase()}_${validatedSpritesheet.commitSha}_${Object.keys(data).length}`
    data[key] = validatedSpritesheet

    const dataDir = new URL(".", DATA_URL)
    const sheetsDir = new URL("spritesheets/", dataDir)
    
    // Ensure directories exist
    const { mkdir } = await import("node:fs/promises");
    await mkdir(sheetsDir.pathname, { recursive: true });

    // Save image file
    const imagePath = new URL(validatedSpritesheet.fileName, sheetsDir)
    await Bun.write(imagePath, imageData)

    // Save metadata
    const content = `// This file is auto-generated by spritesheet-generator. Do not edit manually.\n${JSON.stringify(data, null, 2)}`
    await Bun.write(DATA_URL, content)
  }
}
